# Generated by Django 4.1.1 on 2023-05-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('assembly_id', models.AutoField(primary_key=True, serialize=False)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fabrication',
            fields=[
                ('fabrication_id', models.AutoField(primary_key=True, serialize=False)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('process', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.role')),
            ],
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('subassembly_id', models.AutoField(primary_key=True, serialize=False)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(default='Pending', max_length=50)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subassembly_approvals', to='data_store.user')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.assembly')),
                ('fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.fabrication')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.item')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineUser',
            fields=[
                ('machine_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.user')),
            ],
        ),
        migrations.AddField(
            model_name='fabrication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabrication_approvals', to='data_store.user'),
        ),
        migrations.AddField(
            model_name='fabrication',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.item'),
        ),
        migrations.AddField(
            model_name='fabrication',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.machine'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_approvals', to='data_store.user'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.machine'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.process'),
        ),
    ]
