# Generated by Django 4.1.1 on 2023-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0003_alter_assembly_assembly_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(choices=[('tub', 't1I'), ('pump', 'p1I'), ('spintube', 'st1I'), ('washtube', 'wt1I'), ('balancering', 'br1I'), ('transmissiongear', 'tg1I'), ('plasticbracket', 'pb1I')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(choices=[('tub', 'Tub'), ('pump', 'Pump'), ('spintube', 'Spin Tub'), ('washtube', 'Wash Tub'), ('balancering', 'Balance Ring'), ('transmissiongear', 'Transmission Gears'), ('plasticbracket', 'Plastic Brackets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='process',
            name='process',
            field=models.CharField(choices=[('transmissionassembly', 'Transmission Assembly'), ('electricalassembly', 'Electrical Assembly'), ('tubassemblies', 'Tub assemblies'), ('mechanicalassembly', 'Mechanical assembly'), ('weldassembly', 'Weld Assembly'), ('sportweldassembly', 'Spot Weld Assembly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(choices=[('transmissionassembly', 'ta1P'), ('electricalassembly', 'ea1P'), ('tubassemblies', 'ta2P'), ('mechanicalassembly', 'ma1P'), ('weldassembly', 'wa1P'), ('sportweldassembly', 'swa1P')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.CharField(choices=[('admin', 'a1R'), ('user', 'u1R'), ('fab_manager', 'fm1R'), ('sub_assembly_manager', 'sam1R'), ('assembly_manager', 'am1R'), ('fab_operator', 'fo1R'), ('sub_assembly_operator', 'sao1R'), ('assembly_operator', 'ao1R')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('fab_manager', 'Fabricator Manager'), ('sub_assembly_manager', 'Sub Assembly Manager'), ('assembly_manager', 'Assembly Manager'), ('fab_operator', 'Fabricator Operator'), ('sub_assembly_operator', 'Sub Assembly Operator'), ('assembly_operator', 'Assembly Operator')], max_length=50),
        ),
    ]
