# Generated by Django 4.1.1 on 2023-05-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0004_alter_item_item_id_alter_item_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyProcess',
            fields=[
                ('process_id', models.CharField(choices=[('componentintegration', 'ca1AP'), ('electricaltesting', 'et1AP'), ('compliance', 'c1AP'), ('certificationstandard', 'cs1AP'), ('pivotdome', 'pd1AP'), ('powdercoatingprocess', 'pcp1AP'), ('testingandinspection', 'tai1AP')], max_length=50, primary_key=True, serialize=False)),
                ('process', models.CharField(choices=[('componentintegration', 'Component Integration'), ('electricaltesting', 'Electrical Testing'), ('compliance', 'Complaince'), ('certificationstandard', 'Certification Standards'), ('pivotdome', 'Pivot Dome'), ('powdercoatingprocess', 'Powder Coating Process'), ('testingandinspection', 'Testing and Inspection')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('sub_process_id', models.CharField(choices=[('transmissionassembly', 'ta1P'), ('electricalassembly', 'ea1P'), ('tubassemblies', 'ta2P'), ('mechanicalassembly', 'ma1P'), ('weldassembly', 'wa1P'), ('sportweldassembly', 'swa1P')], default='val', max_length=50, primary_key=True, serialize=False)),
                ('sub_process', models.CharField(choices=[('transmissionassembly', 'Transmission Assembly'), ('electricalassembly', 'Electrical Assembly'), ('tubassemblies', 'Tub assemblies'), ('mechanicalassembly', 'Mechanical assembly'), ('weldassembly', 'Weld Assembly'), ('sportweldassembly', 'Spot Weld Assembly')], default='val', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='assembly',
            name='approval_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='approval_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='approval_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='sub_process',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data_store.subprocess'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.assemblyprocess'),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
