# Generated by Django 4.1.1 on 2023-05-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0005_assemblyprocess_subprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='worker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_worker', to='data_store.user'),
        ),
        migrations.AddField(
            model_name='fabrication',
            name='worker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabrication_worker', to='data_store.user'),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='worker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subassembly_worker', to='data_store.user'),
        ),
    ]
