# Generated by Django 4.1.1 on 2023-05-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0006_assembly_worker_name_fabrication_worker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subassembly',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='subassembly',
            name='fabrication',
        ),
        migrations.DeleteModel(
            name='MachineUser',
        ),
    ]
