# Generated by Django 4.1.1 on 2023-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0007_remove_subassembly_assembly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='edate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='sdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='edate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='sdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='edate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='sdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
